apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-nginx-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: ingress-controller-nginx-ingress
    helm.sh/chart: nginx-ingress-0.14.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ingress-controller
spec:
  externalTrafficPolicy: ""
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  